### PR TITLE
Created log Function

### PR DESCRIPTION
**Pull request by kirubakarrs**
Created log Function. Kindly review & merge.

### CODE REVIEW

**Comment by MrPowers** [comment]
@lizparody - Is your computer ready yet?  Can you review this pull request?

cc: @kirubakarrs

**Comment by LizzParody** [comment]
@MrPowers @kirubakarrs Yes I will review it.

**Review by LizzParody — COMMENTED** [review]
Thank you for contributing @kirubakarrs! great job 🥇

**Comment by kirubakarrs** [comment]
@lizparody Thank you very much!

**Pull request merged**
